language: node_js
node_js:
  - '4'
  - '6'
  - '8'
deploy:
  provider: npm
  email: nwoltman@outlook.com
  on:
    tags: true
  api_key:
    secure: E+WUt9DEQJN9YcuVo5Z2waXaQJmAScoHNZCJnqoAObqaiZKlFWGZFMcAUHFV+xGNcoPlENBhBoADebh9e0JHAqbr3vaIbg8+c71unv4UhdBu1i+BF99SsjF8TZ9AMjpeqfDEy1jntWiqQdmr7C8jHQPmf1ISSmyXCBGaNJpytsweuy67b6OxO6i6s0tyoJkzVaVT5I3lO1rDst2pqjEQOgJOa4rf2Y6ISMnXxhMEk2KqfrNzHNJdvx4zNqStdSno7UWFFwVL6F0la3nQCdTGsUbKc2Z+fzAd+MFHkJ4S5OMt7vd5XnvjL40Uy/QS6Iaqz2ajHsG/TNHik7D4Ye8eljls8k+eu/Nvpa7dVLekw8riGoZ1j37/IXFQMg/XXHQB6Vh86pL/moglSES/t3U9VMCeNh23G4TZQLur+OjAxbyqrQQWEcXFrmT/zzfRdykV1GobbsGipwrEFiL7HA6w9qKW59VMPs0cU5OzaQt9jb/8gbGmOFEYL9heuhaBygmwmYwl/MMQllwFivBrXsbEZqSlEsfguT2iE2dsducFRxpCrQOPRo7tLrmt3mWKEmkJ+uxzAj8gaL9KpNA72SMAQMOjBMImXcoyGAR0FImVV4+JaItgoDfRziT2c91uSiJ3s1F7NEO8x+hZmI9x8QacKTK/1G3dqs0v8ZLXh35SR5k=
