language: node_js
node_js:
  - '0.12'
  - 'iojs'
  - '4'
before_script: npm install -g grunt-cli
deploy:
  provider: npm
  email: nwoltman@outlook.com
  on:
    tags: true
  api_key:
    secure: meyDzXrMYL7gmnhlR6qbrLvccd0tHd86t+axhzl9yBIUviUK2UbYeZqkX6C0BSLqQzjCrzxKTTvjl2fbOH1czlQT4XGQI/1NWpfgnR/fU/IAGxzKex+7inWlrKiBjJJFr4mMbQEKERxvkl+UnC1kBwydk2wbhc1f1peimdcCWyab3jo950ymknCotlGy6+SPX92h5K15wiLloqzBccuLwe/BAnXPWdkxOdNn23Qr3hok4pG+/JU1OK24OsZg+SQtYYW8LKxuDw3OxhyUr3Azgo2XL9tUAh9qMb1riHHHbAVUSuhcjuWv0SYBzwvLLQGbVVbGwvpacYTnJl7lmZuUovzZ347Qupd+ATYLhHlLxccL4wmZ6OhEc7UlL1oLyhv23d4iZc/kZz2ZRywXGqb7BaSX/dfhLin2FcuCcQlad0eT29z730nEMWd5O3nK+5fDcx9ArVLdhEBAJyBIfjUXOqS3j0bNrsH/2NMmzZ0+eQBk/4R/ttA6gXOXWwj8CnWfsJkxLdC9Ier/oK+i5NTa/e6sjyMZMKkiAIFuKtkqNeIdhvyLANJtqBsQr5NjeWEZ6wg+eYRVYsV2Qz2hqrsww4slSCtWI8bV3M9BQh4A2aOZujSIgORs+tnsT8kIiMnlEfUgDSL8J5DIwpeKBIzQbFrf9xSjhO+WochjZRDPi7c=
